#!/usr/bin/env node
/* ===================================================================
   Search pages — run after any content change:   node tools/build-seo.js

   The app lives on one page and routes with #fragments, which search
   engines treat as the same address. So search can only ever see the
   home page. This writes plain HTML that search engines can read
   without running the app:

     c/<slug>/index.html   one overview per course: units, topics and
                           counts, linking into the app
     sitemap.xml           the home page plus every course page
     index.html            the block between <!-- seo:start --> and
                           <!-- seo:end --> inside <main id="app">: the
                           same overview for the home page, shown until
                           the app replaces it

   Only titles and counts go into these pages, never notes or
   questions. tools/check.js warns when they're out of date.
   =================================================================== */
"use strict";
const fs = require("fs"), path = require("path"), vm = require("vm");
const ROOT = path.join(__dirname, "..");
const SITE = "https://iambeniwal.github.io/iitj-bsmt-hub/";

function load() {
  const ctx = {};
  ctx.window = ctx;
  vm.createContext(ctx);
  const run = f => vm.runInContext(fs.readFileSync(path.join(ROOT, f), "utf8"), ctx, { filename: f });
  run("content/program.js");
  const html = fs.readFileSync(path.join(ROOT, "index.html"), "utf8");
  [...html.matchAll(/<script src="(content\/sem\d+\/[^"]+\.js)"><\/script>/g)].forEach(m => run(m[1]));
  return ctx.HUB;
}

const ENT = { amp: "&", lt: "<", gt: ">", quot: '"', nbsp: " ", mdash: "—", ndash: "–", rarr: "→", times: "×", hellip: "…" };
const text = h => String(h).replace(/<[^>]+>/g, "").replace(/&#(\d+);/g, (_, n) => String.fromCodePoint(+n))
  .replace(/&([a-z]+);/g, (m, n) => ENT[n] ?? m).replace(/\s+/g, " ").trim();          // content HTML → plain text
const esc = s => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const n = x => x.toLocaleString("en-IN");
const ld = obj => `<script type="application/ld+json">${JSON.stringify(obj).replace(/</g, "\\u003c")}</script>`;

function courses(H) {
  return H.semesters.flatMap(s => s.courses.map(r => {
    const c = H.courses[r.slug];
    return { r, c, sem: s, url: `${SITE}c/${r.slug}/`,
      units: c.units.map(u => ({ title: text(u.title), topics: (u.topics || []).map(t => text(t.t)) })),
      q: c.questions.length, defs: (c.defs || []).length, traps: (c.traps || []).length };
  }));
}

function coursePage(H, k, all) {
  const P = H.program, { r, sem, units } = k;
  const first = units[0].title, last = units[units.length - 1].title;
  const title = `${r.name} (IIT Jodhpur BSMT): notes, practice questions and mock papers`;
  const desc = `Free revision for ${r.name}, ${sem.label} of IIT Jodhpur's ${P.name}: ${n(k.q)} practice questions, `
    + `${n(k.defs)} flashcards and notes on ${units.length} units, from ${first} to ${last}. Student-made.`;
  const app = path => `../../#/${path}`;
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<!-- generated by tools/build-seo.js from content/: edit the content, then rerun it -->
<title>${esc(title)}</title>
<meta name="description" content="${esc(desc)}">
<link rel="canonical" href="${k.url}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="BSMT Study Hub">
<meta property="og:title" content="${esc(r.name)} · BSMT Study Hub">
<meta property="og:description" content="${esc(desc)}">
<meta property="og:url" content="${k.url}">
<meta property="og:image" content="${SITE}assets/og.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">
<meta name="theme-color" content="#0E1524">
<link rel="icon" href="../../assets/icon-48.png" sizes="48x48" type="image/png">
<link rel="icon" href="../../assets/icon-192.png" sizes="192x192" type="image/png">
<link rel="apple-touch-icon" href="../../assets/icon-180.png">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,500;12..96,700;12..96,800&family=Source+Sans+3:ital,wght@0,400;0,600;0,700;1,400&family=JetBrains+Mono:wght@400;700&display=swap">
<link rel="stylesheet" href="../../assets/hub.css">
<script src="../../assets/analytics.js"></script>
${ld({ "@context": "https://schema.org", "@graph": [
  { "@type": "WebPage", "@id": k.url, url: k.url, name: title, description: desc, inLanguage: "en",
    isPartOf: { "@type": "WebSite", "@id": SITE + "#site", name: "BSMT Study Hub", url: SITE } },
  { "@type": "BreadcrumbList", itemListElement: [
    { "@type": "ListItem", position: 1, name: "BSMT Study Hub", item: SITE },
    { "@type": "ListItem", position: 2, name: r.name, item: k.url }] }] })}
</head>
<body>
<header class="topnav"><div class="topbar"><a class="brand" href="../../">BSMT<span>Hub</span></a>
  <div class="navrow"><a href="../../">Home</a><a href="${app("bank?c=" + r.slug)}">Bank</a></div></div></header>
<main class="wrap seo">
  <header class="mast">
    <div class="crumbs"><a class="backlink" href="../../">← BSMT Study Hub</a></div>
    <div class="eyebrow">IIT Jodhpur · ${esc(P.name)} · ${esc(sem.label)}</div>
    <h1>${esc(r.name)}</h1>
    <p class="sub">Revision for ${esc(r.name)}: notes on ${units.length} units, ${n(k.q)} practice questions with explanations,
      ${n(k.defs)} flashcards and ${n(k.traps)} common traps, plus timed mock papers marked like the real quiz (${esc(P.marking.note)}).
      Free, and it remembers what you get wrong.</p>
    <p class="cta"><a class="btn" href="${app("c/" + r.slug)}">Open ${esc(r.short)} in the hub</a>
      <a class="btn ghost" href="${app("practice?c=" + r.slug)}">Practise questions</a></p>
  </header>
  <section>
    <div class="sechead"><h2>What's covered</h2></div>
    <ol class="seo-units">
${units.map(u => `      <li><h3>${esc(u.title)}</h3>${u.topics.length ? `<p>${u.topics.map(esc).join(" · ")}</p>` : ""}</li>`).join("\n")}
    </ol>
  </section>
  <section>
    <div class="sechead"><h2>Other ${esc(sem.label)} courses</h2></div>
    <ul class="seo-links">
${all.filter(o => o !== k).map(o => `      <li><a href="../${o.r.slug}/">${esc(o.r.name)}</a> <span>${n(o.q)} questions</span></li>`).join("\n")}
    </ul>
  </section>
  <footer>
    <p>Student-made study aid, not official IIT Jodhpur or Masai School course material, and not affiliated with or endorsed by
      either. Exam facts come from each course's official LMS announcement; always confirm against the LMS.</p>
    ${P.requestForm ? `<p>Something wrong, a question, or a request about your data? Use the <a href="${esc(P.requestForm)}" rel="noopener">contact form</a>;
      every message gets a reply within ${P.replyDays} days.</p>` : ""}
    <p class="licence">Notes and questions licensed <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" rel="noopener">CC&nbsp;BY-NC-SA&nbsp;4.0</a>.
      Underlying course material remains the property of IIT Jodhpur and the respective faculty and is not licensed here.
      <a href="../../#/privacy">Privacy notice</a>.</p>
  </footer>
</main>
</body>
</html>
`;
}

/* the home page's own overview, inside <main id="app"> until the app takes over */
function homeBlock(H, all) {
  const total = all.reduce((s, k) => s + k.q, 0);
  return `<!-- seo:start (generated by tools/build-seo.js) -->
<header class="hub-mast">
  <div class="eyebrow">IIT Jodhpur · ${esc(H.program.name)} · Batch ${esc(H.program.batch)}</div>
  <h1>Study Hub</h1>
  <p class="sub">Notes, a ${n(total)}-question bank, flashcards and timed mock papers for every course, plus a record of what you keep getting wrong.</p>
</header>
<section>
  <div class="sechead"><h2>Courses</h2></div>
  <ul class="seo-links">
${all.map(k => `    <li><a href="c/${k.r.slug}/">${esc(k.r.name)}</a> <span>${n(k.q)} questions · ${k.units.length} units</span></li>`).join("\n")}
  </ul>
</section>
<!-- seo:end -->`;
}

function render() {
  const H = load(), all = courses(H), out = {};
  for (const k of all) out[`c/${k.r.slug}/index.html`] = coursePage(H, k, all);
  out["sitemap.xml"] = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${[SITE, ...all.map(k => k.url)].map(u => `  <url><loc>${u}</loc></url>`).join("\n")}
</urlset>
`;
  const index = fs.readFileSync(path.join(ROOT, "index.html"), "utf8");
  const re = /<!-- seo:start[\s\S]*?<!-- seo:end -->/;
  if (!re.test(index)) throw new Error("index.html has no <!-- seo:start --> … <!-- seo:end --> block");
  out["index.html"] = index.replace(re, homeBlock(H, all));
  return out;
}

/* paths whose file on disk differs from what render() would write */
function stale() {
  const out = render();
  return Object.keys(out).filter(f => {
    try { return fs.readFileSync(path.join(ROOT, f), "utf8") !== out[f]; } catch (e) { return true; }
  });
}

module.exports = { render, stale };

if (require.main === module) {
  const out = render();
  for (const [f, body] of Object.entries(out)) {
    const p = path.join(ROOT, f);
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, body);
  }
  console.log(`wrote ${Object.keys(out).length - 2} course pages, sitemap.xml and the index.html block`);
}
